//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HvkAccount
    {
        public int HvkID { get; set; }
        public string HvkUserName { get; set; }
        public string HvKPassword { get; set; }
        public string HvkFullName { get; set; }
        public string HvkEmail { get; set; }
        public string HvkPhone { get; set; }
        public Nullable<bool> HvkAtive { get; set; }
    }
}
