//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkLesson07Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hvkKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hvkKhoa()
        {
            this.hvkSinhVien = new HashSet<hvkSinhVien>();
        }
    
        public string HvkKH { get; set; }
        public string HvkTenKH { get; set; }
        public Nullable<bool> HvkTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hvkSinhVien> hvkSinhVien { get; set; }
    }
}
