//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkLesson07Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hvkSinhVien
    {
        public string HvkMaSV { get; set; }
        public string HvkHoSV { get; set; }
        public string HvkTenSV { get; set; }
        public Nullable<System.DateTime> HvkNgaySinh { get; set; }
        public Nullable<bool> HvkPhai { get; set; }
        public string HvkPhone { get; set; }
        public string HvkEmail { get; set; }
        public string HvkMaKH { get; set; }
    
        public virtual hvkKhoa hvkKhoa { get; set; }
    }
}
