//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkK22CNT4Lesson12_2210900109.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hvk_TacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hvk_TacGia()
        {
            this.Hvk_Sach = new HashSet<Hvk_Sach>();
        }
    
        public string Hvk_MaTG { get; set; }
        public string Hvk_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hvk_Sach> Hvk_Sach { get; set; }
    }
}
