//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkK22CNT4Lesson12_2210900109.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hvk_Sach
    {
        public string Hvk_MaSach { get; set; }
        public string Hvk_TenSach { get; set; }
        public Nullable<short> Hvk_SoTrang { get; set; }
        public Nullable<System.DateTime> Hvk_NamXB { get; set; }
        public string Hvk_MaTG { get; set; }
        public Nullable<bool> Hvk_TrangThai { get; set; }
    
        public virtual Hvk_TacGia Hvk_TacGia { get; set; }
    }
}
