//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkK22CNT4Lesson12_2210900109.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoangVanKhai_2210900109Entities : DbContext
    {
        public HoangVanKhai_2210900109Entities()
            : base("name=HoangVanKhai_2210900109Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hvk_Sach> Hvk_Sach { get; set; }
        public virtual DbSet<Hvk_TacGia> Hvk_TacGia { get; set; }
    }
}
