//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkK22CNT4Lesson11Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HvkK22CNTLesson11DbEntities : DbContext
    {
        public HvkK22CNTLesson11DbEntities()
            : base("name=HvkK22CNTLesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HvkCategory> HvkCategory { get; set; }
        public virtual DbSet<HvkProduct> HvkProduct { get; set; }
    }
}
