//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkK22CNT4Lesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HvkCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HvkCategory()
        {
            this.HvkProduct = new HashSet<HvkProduct>();
        }
        [Display(Name="Mã danh m?c")]

        public int HvkID { get; set; }
        [Display(Name = "Tên danh m?c ")]
        public string HvkCateName { get; set; }
        [Display(Name = "Tr?ng thái ")]

        public Nullable<bool> HvkStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HvkProduct> HvkProduct { get; set; }
    }
}
