//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HvkK22CNT4Lesson11Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HvkProduct
    {
        public string Hvkid2210900109 { get; set; }
        public string HvkProName { get; set; }
        public Nullable<int> HvkQty { get; set; }
        public Nullable<double> HvkPrice { get; set; }
        public Nullable<int> HvkCateId { get; set; }
        public Nullable<bool> HvkActive { get; set; }
    
        public virtual HvkCategory HvkCategory { get; set; }
    }
}
